--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AstroKotlin/AFloatingText
build-by-default: false
branches:
- main
projects:
  AFloatingText:
    path: ""
    icon: icon.png
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^2.5.6
        branch: "main"
...
